### ISSUE TITLE
Installation (via yarn install) hangs with Yarn 1.x (classic)

### ISSUE THREAD

**Issue by kevinbluer** [MetaMask/snap-box#9]
## Issue

If you attempt `truffle unbox` (or a manual `yarn install`) with yarn classic (`v1.x`) installed it currently hangs at the following: 

![image](https://user-images.githubusercontent.com/210755/202290654-b0705b0e-68bd-44bf-97f1-6bc239f5c221.png)

It's possible that the [packageManager](https://github.com/MetaMask/snap-box/blob/main/package.json#L46) reference in the `package.json` is causing a conflict, although I'll do a bit more digging as happy to help troubleshoot.

**Comment by kevinbluer** [comment]
After a bit more digging it doesn't look like there's going to be any way around the dependency on `yarn v3.x` without it becoming a bit of a rabbit hole (given the use of `foreach` within the workspace related commands, etc). As such just wondering if it might be easiest to add something like the following to the [Pre-requisites](https://github.com/MetaMask/snap-box#pre-requisites) section:

```
Note this box also requires yarn `v3.x`. If you're using Node 16 or later you'll be able to enable it with `corepack enable`
```

In addition, just wondering if we should remove the `yarn install` from the [post-unpack hook](https://github.com/MetaMask/snap-box/blob/main/truffle-box.json#L10) to mitigate the hang should the user have 1.x installed and / or if they don't have `yarn` installed at all?

**Comment by michaeljohnbennett** [comment]
a quick peruse of the yarn 3 docs says you will also need to enable a workpsace-tools plugin too to get this working. 

https://yarnpkg.com/api/modules/plugin_workspace_tools.html

So yeah, not really intuitive for someone to install/work with easily without yarn 3.x isntalled and configured properly.

**Comment by Montoya** [comment]
I have attempted to resolve this issue in this PR https://github.com/MetaMask/snap-box/pull/11
